# Generated by Django 4.2.11 on 2024-04-27 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True, max_length=256, null=True)),
                ('telefone', models.TextField(max_length=11)),
                ('nome', models.TextField(blank=True, max_length=128, null=True)),
                ('cep', models.TextField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('endereco', models.TextField(blank=True, max_length=128, null=True)),
                ('numero', models.IntegerField()),
                ('bairro', models.TextField(blank=True, max_length=128, null=True)),
                ('cidade', models.TextField(blank=True, max_length=128, null=True)),
                ('estado', models.TextField(blank=True, max_length=2, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('termos', models.BooleanField(default=False)),
            ],
        ),
    ]
